# Generated by Django 4.2.1 on 2023-06-07 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Profile_img',
            field=models.ImageField(blank=True, default='profiles/default.png', null=True, upload_to='profiles'),
        ),
    ]
